name: Build
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: npm run lint
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   env:
  #     SKIP_ENV_VALIDATION: true
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18

  #     - name: Download deps
  #       uses: bahmutov/npm-install@v1

  #     - name: Type check
  #       run: npm run test
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SKIP_ENV_VALIDATION: true
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build
